import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import Papa from 'papaparse';

type SocketHeadCsvRow = Record<string, string>;

const currentDirectory = dirname(fileURLToPath(import.meta.url));
const sourcePath = resolve(currentDirectory, '../../data/socket-head-cap-screws.csv');
const outputPath = resolve(currentDirectory, '../src/data/socketHeadPrototypeCatalog.ts');
const csv = readFileSync(sourcePath, 'utf8');
const parsed = Papa.parse<SocketHeadCsvRow>(csv, { header: true, skipEmptyLines: true });

if (parsed.errors.length > 0) {
  throw new Error(`Unable to parse socket-head catalog: ${parsed.errors[0].message}`);
}

function clean(value: string | undefined): string {
  const trimmed = value?.trim();
  return trimmed && trimmed !== '-' ? trimmed : '';
}

const records = parsed.data.map((row, index) => {
  const required = ['sku', 'thread_size', 'length', 'material'] as const;
  const missing = required.filter(field => !row[field]?.trim());

  if (missing.length > 0) {
    throw new Error(`Row ${index + 2} missing required fields: ${missing.join(', ')}`);
  }

  const head = [clean(row.socket_head_profile), clean(row.head_type)].filter(Boolean).join(' ') || 'Socket';

  return {
    partNumber: `PROTO-SHCS-${row.mcmaster_pn || row.sku}`,
    ...(clean(row.mcmaster_pn) ? { mcmaster: clean(row.mcmaster_pn) } : {}),
    title: clean(row.title),
    family: 'socket',
    type: 'Socket Head Cap Screw',
    thread: clean(row.thread_size),
    pitch: clean(row.thread_pitch),
    length: clean(row.length),
    head,
    material: clean(row.material),
    finish: clean(row.finish),
    drive: clean(row.drive_style),
    strength: clean(row.fastener_strength_grade_class) || clean(row.tensile_strength) || clean(row.hardness),
    standard: clean(row.specifications_met),
    sourceSku: clean(row.sku),
    isPrototype: true,
    demo: true,
    synthetic: true,
    provenanceKind: 'internal-demo-seed',
    provenanceNote: 'Demo configuration facts imported from reviewed PartSource CSV packet socket-head-cap-screws.csv. McMaster numbers are search clues only.',
    verification: 'demo-only',
  };
});

const output = `// Generated by scripts/generate-socket-head-prototype-catalog.ts. Do not edit manually.\n\nexport type SocketHeadPrototypeRecord = {\n  partNumber: string;\n  mcmaster?: string;\n  title: string;\n  family: 'socket';\n  type: 'Socket Head Cap Screw';\n  thread: string;\n  pitch: string;\n  length: string;\n  head: string;\n  material: string;\n  finish: string;\n  drive: string;\n  strength: string;\n  standard: string;\n  sourceSku: string;\n  isPrototype: true;\n  demo: true;\n  synthetic: true;\n  provenanceKind: 'internal-demo-seed';\n  provenanceNote: string;\n  verification: 'demo-only';\n  offers?: never;\n};\n\nexport const SOCKET_HEAD_PROTOTYPE_CATALOG: SocketHeadPrototypeRecord[] = ${JSON.stringify(records, null, 2)};\n`;

writeFileSync(outputPath, output);
