/**
 * Generated by `npm run catalog:build-real` (u1). Do not edit by hand.
 * Dev-only catalog release identity; the artifact is served exclusively
 * by the Vite dev server and never enters the production build.
 */
export const REAL_CATALOG_RELEASE_ID = 'partsource.dev.cofounder-screws.v1';
export const REAL_CATALOG_DIGEST = 'sha256:7b1f12c9de024f498805f99f74b9846d9be12f694858383271ea9df0d85f1aef' as const;
export const REAL_CATALOG_URL = 'catalog/real-screws-v1.json';
export const REAL_CATALOG_NOTICE = "Cofounder-provided dataset for local development — not reviewed for public release; origin confidential.";
